"""Create models

Revision ID: 7907a1e0a0de
Revises: 
Create Date: 2022-11-20 21:12:38.454115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7907a1e0a0de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=True),
    sa.Column('firstname', sa.String(length=45), nullable=True),
    sa.Column('lastname', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=45), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=45), nullable=True),
    sa.Column('isAdmin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Paymethod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardNumber', sa.String(length=45), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Transfer',
    sa.Column('transferValue', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('datetime', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.Enum('failed', 'approved', 'denied'), nullable=True),
    sa.Column('source_paymethod_id', sa.Integer(), nullable=True),
    sa.Column('destination_paymethod_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destination_paymethod_id'], ['Paymethod.id'], ),
    sa.ForeignKeyConstraint(['source_paymethod_id'], ['Paymethod.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Transfer')
    op.drop_table('Paymethod')
    op.drop_table('User')
    # ### end Alembic commands ###
